### ISSUE TITLE
Help something is wrong

### ISSUE THREAD

**Issue by Lionharth** [linsomniac/spotify_to_ytmusic#10]
![bild](https://github.com/linsomniac/spotify_to_ytmusic/assets/90109349/cd4b6349-5769-4c49-a745-117c48bff51b)
Idk what's wrong

**Comment by linsomniac** [comment]
Looks like there is no artist associated with that track, let me dig into it a bit...

**Comment by linsomniac** [comment]
You can try running that again, because I ran a search for that track ("Cherry On Top") and it seemed to correctly look it up.  But that error indicates that there were no artists associated with the song it found on YTMusic.  I've released a new version of the code which prevents this error from being fatal (instead displaying "<Unknown>").  Give that a shot.

**Comment by Lionharth** [comment]
Thank you! I'm running it right now, so I'll update you on how it goes. Anyway, thanks for being so quick!
