### ISSUE TITLE
Instructions Confusion

### ISSUE THREAD

**Issue by Galetron** [linsomniac/spotify_to_ytmusic#17]
I am very bad with understanding python, I haven't yet began to learn how python works, and almost every instruction on the page is difficult for me to understand due to that, I hate to report this as an issue, but I need some help setting this up, and don't know where to ask about the topic of help on using this other than here, I'm primarily trying to get a grasp on PIP and how to use that, but I'm also trying to do the "run from source" method to try to use the GUI version, but that is a bit disconnected from this topic specifically, I just need some help either getting this or the GUI version set up, because I really want to leave Spotify, their pushing of premium is just very annoying, but I don't know how to do it myself, and need help using this, which seems to be the overall best option, because moving over a thousand songs from Spotify to Youtube music would take literal weeks of my life, thank you for the help, anyone who does help, and I'm very sorry to have to add this issue to the spotify_to_ytmusic project linsomniac.

**Comment by Yoween** [comment]
Hey ! I'm the one who made the GUI version.
So first of all, you need to have python installed from the website, not Microsoft store. I personally have python 3.10.2 because that's the one shipped with my linux.
Then you need to install the library `ytmusicapi` from pip, using `pip install ytmusicapi`
If you are using Linux, you may not have `tkinter` installed. To install it, you need to find your python version, by typing `python3 -V` in a terminal. For example, mine is 3.10.2, so I typed `sudo apt-get install python3.10-tk`. If you have 3.6, you install 3.6-tk, etc...
Then double click the `start.vbs` file on window or type `chmod +x start.sh` then `./start.sh` if on Linux.
And then, I think the GUI is very straightforward.
If you have any questions, feel free to ask and I'll gladly help you !

**Comment by Galetron** [comment]
Thank you Yoween for helping, I'm on windows, but I don't understand how to do pip stuff, as I mentioned, since I don't know much about Python, I don't know much about Python related things, although I looked up what you said, and got a site called PyPI, is that where I can get it from, otherwise I'm not quite sure how to get the library, it shows some stuff about using commands on the pages, and I'm not sure if that's the next step or not, so I attempted to do that through Python (downloaded it from the official Python website) and Command Prompt, neither helped me add it, right now I'm stuck on getting the pip, so a run through on how to do that would be helpful.

**Comment by Yoween** [comment]
Okay so getting python from the official website is good. PyPi is a website that lists every package (library) installable using the `pip` command. You install the said libraries by using the command line tool embedded in python called `pip` by typing in a command prompt (cmd) `pip install` then the name of the package you're looking for.
But first, let's check if python is correctly installed. For that, you need too open a cmd, and type `python -V`. If this shows the version of python you've downloaded, it's good. Otherwise, you can see every installed versions of python by typing `where python`. If there's only one line and it is the Microsoft store one, then either the installation went wrong or python wasn't added to $PATH. I recommend looking up how to add python to path of the internet since explaining it here would be a bit long. (but I promise it's not that hard !)
Now you made sure python was correctly installed, you need to check if this is the case for pip too. Just type `pip -V`. If this shows a version of pip linked to the version of python you installed, then it works !
If everything went fine, you can install the only decency needed: `ytmusicapi`. Do you remember what I said earlier about installing packages?
And then, you can just double click `start.vbs`! 
Also, do not open bat or vbs files you don't know/trust. If you have any doubt, open it with your favourite text editor and look what it does !
For example, mine creates a new shell and starts the `gui.py` file. You can do the same thing by opening a cmd in the folder where the program is located, then typing `python gui.py` ! It's just a matter of convenience, since the script hides the cmd window !

**Comment by Yoween** [comment]
I am going to bed now, but I'll be there tomorrow morning if you have any more questions!

**Comment by Galetron** [comment]
Thank you for the continued help, it says I don't have a version of Python, I do, so I'll continue with what you said, late good night, I'll comment again if I still need help with something

**Comment by linsomniac** [comment]
Unfortunately, Windows isn't quite as standardized as Linux for the python installs, so what you need to do will vary, depending on the installation.  Perhaps the instructions related to the installation can help you out with how to run Python?

The first step is you need to be able to open a command-line (like PowerShell) and run Python.  This might be by typing: "python", "python3", "python310", or "python.exe" or maybe "C:/python310/bin/python.exe".  Do you have "choco" on your system?  That is one way to install Python on Windows and I have used that successfully in the past for other projects.  I'm sorry, I don't have a windows machine I can use here to run tests on.

Once you can run Python from the CLI, you should be able to run your python with the arguments "-m pip install spotify2ytmusic" to download and install it.

Currently, this project doesn't really provide an easy way to just run it without some knowledge of Python.  Yoween has made some steps in the right direction towards that.  I have some ideas on another way, but that is going to take significant work.

But, let's see if we can help you out.

**Comment by Galetron** [comment]
Hello linsomniac, I was able to successfully launch Yoween's fork of this, my issue with my it wasn't working was over a problem with my device not putting python within its environment variables, although making sure I can launch yours would ensure that I fixed all the python troubles, thank you two for the hasty and supportive comments, and if this was just a small issue on my end, hopefully I can be an example for how to fix it.

**Comment by linsomniac** [comment]
What did you need to do to get it resolved?  I'd like to add it to the documentation.  Can you propose any sort of "FAQ" answer for it?

Hopefully in the short term Yoween's code will join us in here, so it'll all be unified.

**Comment by Galetron** [comment]
To sum it up, on my windows 10 device I installed the latest version of Python, it didn't register on my device, so I followed a video (https://www.youtube.com/watch?v=4bUOrMj88Pc) to solve my problem, and added Python to my computer's Path Environment Variable physically, the video should be a really good exact guide on what to do, hopefully this can be helpful, thanks for all the help.

**Comment by Galetron** [comment]
One other question, I might ask this here, or in another issue, depends on whether it seems like a large enough problem, but it involves Yoween's fork of this, when I use the "Copy a specific playlist" tab, and input the ID listed from listing playlists, and it just sends an empty line, I don't know if I need to load all playlist songs first, but I have some random playlists everywhere, and it would take double, maybe triple the amount of time to load all of them instead of just one

**Comment by Yoween** [comment]
Hello ! Glad you made it work ! The issue you're talking about is a known issue, however I thought I had fixed it... I'll look more in depth in a few hours!

**Comment by Yoween** [comment]
Hey ! This is fixed in my latest commit ! Just re-download the zip file and replace the existing files by the new ones.

**Comment by Galetron** [comment]
I tried it, and based on my current testing, it is working as planned, my test isn't done loading yet, but it should easily port most of the songs to the Youtube music playlist, which means it seems to be fixed, I'll send one more message here if my continued testing has a problem, or if it seems like all problems are resolved, you two are really great people, and this is an honest life saver, transferring like almost 1500 songs would have been hell, and many hours of my life, and this brings that time down to like 10 minutes, honest thanks from me.

**Comment by Yoween** [comment]
Hello! I'm glad it works now! If you stumble across any issues, feel free to open a new separate issue, so we can close this one. Have a great day!
